#!/usr/bin/env node
// vi:syntax=javascript

'use strict';

var fs = require('fs'),
    dox = require('dox'),
    join = require('path').join;

var find = require('lodash-node/modern/collections/find'),
    where = require('lodash-node/modern/collections/where'),
    map = require('lodash-node/modern/collections/map'),
    curry = require('lodash-node/modern/functions/curry'),
    template = require('lodash-node/modern/utilities/template');

/**
 * @function tag
 * @param {String} type tag type
 * @param {Object} doc single index from dox.parseComments
 * @return {*}
 */
function tag(type, doc) {
    return (find(doc.tags, { type: type }) || {}).string;
}

/**
 * @function tags
 * @param {String} type tag type
 * @param {Object} doc single index from dox.parseComments
 * @return {Array}
 */
function tags(type, doc) {
    return where(doc.tags, { type: type });
}

/**
 * documents a file
 * @function document_class
 * @param {String} file
 * @param {String} tmpl template
 * @return {String} makedown representation of yuidoc documentations
 */
function document_class(file, tmpl) {
    var comments = dox.parseComments(fs.readFileSync(file).toString()),
        base = find(comments, { isConstructor: true }),
        methods = where(comments, curry(tag)('method'));

    return !methods.length ? '' : template(tmpl, {
        base:  {
            name: base ? tag('class', base) : file,
            link: base && tag('link', base)
        },
        methods: map(methods, function (method) {
            return {
                name: tag('method', method),
                link: tag('link', method),
                params: tags('param', method)
            };
        })
    });
}

/**
 * @function make_doc
 * @param {String} source file
 * @param {String} tmpl_str
 */
function make_doc(source, tmpl_str) {
    if (fs.statSync(source).isFile()) {
        console.log(document_class(source, tmpl_str));
    } else if (fs.statSync(source).isDirectory()) {
        fs.readdirSync(source).forEach(function (file) {
            make_doc(join(source, file), tmpl_str);
        });
    }
}

if (!module.parent) {
    var argv = require('minimist')(process.argv.slice(2)),
        sources = argv._,
        tmpl_default = join(__dirname, 'templates', '/simple.md'),
        tmpl_file = argv.t || argv.template || tmpl_default,
        tmpl_str = fs.readFileSync(tmpl_file).toString();

    if (argv.h || argv.help) {
        console.log('Usage: text-documentor [FILE1 [FILE2 [...]]]')
        console.log('');
        console.log(' options:');
        console.log('   - t|template      # template file');

        process.exit(0);
    }

    sources.forEach(function (source) {
        make_doc(source, tmpl_str);
    });
}

module.exports = document_class;
